train:
  optimizer: 'adam'
  adam: 0.001
  adabound:
    initial: 0.001
    final: 0.05
---
model:
  channel: 78 # 'small regime'
  classes: 1000
  graph0: ''
  graph1: ''
  graph2: ''
---
log:
  chkpt_dir: 'chkpt'
  log_dir: 'logs'
